groups:
  - name: CanaryCanarded
    rules:
    - alert: CanaryCanarded
      expr: |
        up{slug="canari"} == 0
      for: 1m
      labels:
        severity: page
      annotations:
        summary: Math has gone haywire on us
        description: My Description

  - name: Canary
    rules:
    - alert: Canari status code is not 404
      expr: probe_http_status_code{slug="canari"} != 404
      for: 1m
      labels:
        severity: page
        sendto: telegram
      annotations:
        summary: Canari HTTP status is not 200
        description: "Expr is probe_http_status_code{slug='canari'} != 404"
