groups:
  - name: Site not 200
    rules:
    - alert: Site status code is not 200
      expr: probe_http_status_code == 200
      for: 1m
      labels:
        severity: page
        sendto: telegram
      annotations:
        summary: "HTTP status of {{$labels.instance}} is not 200"
        description: "{{$labels.instance}} of job {{$labels.job}} has not HTTP status == 200 for more than 5 minutes."

  - name: Site down
    rules:
    - alert: Site down
      expr: up == 0
      for: 5m
      labels:
        severity: page
        sendto: telegram
      annotations:
        summary: "Instance {{$labels.instance}} down ({{$labels.slug}})"
        description: "{{$labels.instance}} of job {{$labels.job}} has been down for more than 5 minutes ({{$labels.slug}})."
