{%raw%}
groups:
  - name: Site not 200
    rules:
    - alert: Site status code is not 200
      expr: probe_http_status_code{job="wordpresses@epfl",origin="noc-zurich"} != 200 and probe_http_status_code{job="wordpresses@epfl",origin="noc-zurich"}  != 0
      for: 1m
      labels:
        severity: page
        sendto: telegram
      annotations:
        summary: 'HTTP status of {{$labels.instance}} is not 200 ({{$labels.wp_env}})'
        description: '{{$labels.instance}} of job {{$labels.job}} has HTTP status == {{ $value }} for more than 1 minute (on env: {{$labels.wp_env}}).'
{%endraw%}