version: '3'
services:
  blackbox-exporter:
    container_name: "{{ container_prefix }}blackbox-exporter"
    image: prom/blackbox-exporter
    volumes:
      - ./config:/config
    command: --config.file=/config/blackbox.yml
    restart: always
    networks:
      - {{ traefik.network }}
      - default
    labels:
      - "traefik.domain={{ frontend.domain }}"
      - "traefik.frontend.rule=Host:bbe.{{ frontend.domain }}"
      - "traefik.docker.network={{ traefik.network }}"
      - "traefik.enable=true"
      - "traefik.port={{ bbe.port }}"
      - "traefik.frontend.auth.basic={{ frontend.htpass | htpasswd }}"

networks:
  {{ traefik.network }}:
    external: true
