---
# This file contains eyaml encrypted records. Edit with `eyaml edit`

prometheus:
  port: 9090

urls:
  fsd:
    - name: gitlab
      slug: gitlab
      url: https://gitlab.epfl.ch
    - name: go
      slug: go
      url: https://go.epfl.ch
    - name: igm
      slug: igm
      url: https://igm.epfl.ch
    - name: it
      slug: it
      url: https://it.epfl.ch
    - name: sti
      slug: sti
      url: https://sti.epfl.ch
  c2c:
    - name: actu
      slug: actu
      url: https://actu.epfl.ch
    - name: memento
      slug: memento
      url: https://memento.epfl.ch
    - name: people
      slug: people
      url: https://people.epfl.ch
    - name: epfl-about
      slug: www.epfl.ch_about
      url: https://www.epfl.ch/about/fr/a-propos/
    -
      url: https://www.epfl.ch/campus/associations/list/ishigo-g/
      slug: ishigo-g
    -
      url: https://www.epfl.ch/campus/associations/list/ishigo-g/redirect
      slug: ishigo-g_redirect
    -
      url: https://www.epfl.ch/campus/associations/list/ishigo-g/B117
      slug: ishigo-g_B117
    -
      url: https://www.epfl.ch/campus/associations/list/ishigo-g/page-148545-en-html/page-154212-en-html/
      slug: ishigo-g_page
    -
      url: https://www.epfl.ch/campus/associations/list/ishigo-g/memento/
      slug: ishigo-g_memento
    -
      url: https://www.epfl.ch/campus/associations/list/ishigo-g/people/
      slug: ishigo-g_people
    -
      url: https://www.epfl.ch/campus/associations/list/ishigo-g/actu/
      slug: ishigo-g_actu
    -
      url: https://www.epfl.ch/campus/associations/list/ishigo-g/cover/
      slug: ishigo-g_cover
    -
      url: https://www.epfl.ch/campus/associations/list/ishigo-g/hero/
      slug: ishigo-g_hero
    -
      url: https://www.epfl.ch/campus/associations/list/ishigo-g/card/
      slug: ishigo-g_card
    -
      url: https://www.epfl.ch/campus/associations/list/ishigo-g/gal/
      slug: ishigo-g_gal
    -
      url: https://www.epfl.ch/campus/associations/list/ishigo-g/infoscience/
      slug: ishigo-g_infoscience

  veritas: "{{ sites_from_veritas.stdout | default('[]') | from_json }}"

c2c:
  prefix: vpsi_wwp_federation
  metrics:
    - probe_dns_lookup_time_seconds
    - probe_duration_seconds
    - probe_http_content_length
    - probe_http_duration_seconds
    - probe_http_last_modified_timestamp_seconds
    - probe_http_status_code
    - probe_http_redirects
    - probe_failed_due_to_regex
    - probe_http_ssl
    - probe_http_version
    - probe_ip_protocol
    - probe_ssl_earliest_cert_expiry
    - probe_success

auth:
  legacy:
    username: "{{ 'ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAYIMx1PuCr7APQ7pZADN9QW68RnD9Jyv+oUcwIaTh5bpn4mCMMy6KNZz3wa9U62FTQ3TQSx/rrC7Zmm7o1UF5MuxxR34mvsJovL/uxHLXrzRK96suiIAZp7hm2tNTMmmI9wh0zEgxiaP5g8FJWIr5TAobjdpPabJ9uB4kVv7zHhSd3kOEFwV/AZylBSzQg/Abv6IMDG9hZUt2awL9UQZMgm+5MLtMAIkUnwVHkJRHR+k849HSaAbJJz2pfFA74YaiPCkvabZgYGn8MIaNvVYBdGd5zR/YVYfA95BP7sqIpFbSNLsIug9srsEAFD661LzTKkl5RFiioOlLPzpJfal1UzA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBBc+xVDHObQw9nhusvZHKF6gBChhjI/OXim7dBOrSPEQEdl]' | eyaml }}"
    password: "{{ 'ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEApMuiCPiPcXbiXwPBkyXH8lNv98JCMlhKi1FbGI3of41XcVnHb58RW4+4pBwmuIhFqfbhqx6e/vkpanMcaj5OENTVAAqAk+sCPVoYpChD1JtGQTBA3Snnj9AIM0JHTAvgGVHG+RkQXwZB60nWE+DkaBKJ8N1J4zrXALiGZfbXRVwuRhbHZPDfVYv9vAntIrqtbhv1oG6pYzGdAl4RS0HEzKPR45YeuSrZePuxSRIC5X90VdNQe54k3ADaWp2qiZqEXAZ/RtNBnlzt/bk3OtqthhvHMsoY2Vh4VbdHnRiG90wIK2v8i2nVXzv+CgGpTP3pkW4EkSkTAuvz6Tzc3EXYDDBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBBGuuO1AX1yeU2njDQ2WSdHgCCuakh3gBOmNKwZjzDdyf3aIv4eOpYLiXFJkRf1VJoFBQ==]' | eyaml }}"
  gitlab:
    username: "{{ 'ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAYsgvRWHm5Z4aUo7WWMmIQpuaAvw+0gje91nu/3o4+MtadCmFGl+lyPD9M8Mkm134Sr3NdpxeBER/2EofxK2iij18zKF9E3+UKtYcddhMV2excEvaSknEgpMjBBq04DIMnoVoWWF9lcsL06JLDqDVr4/3yQzASpJMmR0SoTxAxmijMsdIvifl3XrvigDuAqd/fdKzRij9fLYrXoCdhW3w2RvNN9LL0kFwdzju2RXvOqE8QO+xowv4hnE/EitymL7QY26rWNQ8eYl34W8UpZSGGFuRQ/CxsySAD+ykLOJMDVr6D78O/a72uMhmEj+fWRRMRrhMo7XzqxCQmVweUsQp+TA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBCrMQZE9qIs7lsY6nVPTGO9gBDYvp3colgbuwJqL5+TEDqA]' | eyaml }}"
    password: "{{ 'ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAnkJBs4kc9Sqv5IAUWTPhI7ES4X3HMa0ApIlTBzY0/XMILHHlbj61FSFeg1Ddq8O7MZc8O+I7rOwNiDwCyj/XKfr1dAgt5LAcJWJXETkVxinsyY/zFgqNExVBYlrQk+r4NL/gTmOYS/LbQz1pw7CFFC5Hcgf7vTMz5ddvMljlw9ovtjzc47bP1N4xKxf+/CdZ5LnKveePnysdyu90uPZ1WbupumPsl0Y8GdBAOkeKlLy12MKQfiRpBM2W7A1v3ZiuV+Oq5CnQ0Uu4NyFURUX9FXi5I3qZzMlxW53JARL1xH1eA5UZMqsn/TwawEo4eqrONhwyz+vJ6DXCIZ9VX1lpLzBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBABizNYHbEzygJ+nbiyJ23lgCAdLlpAVEXZgXfPIskZbxicRyx6c3yktVXli+egko7czQ==]' | eyaml }}"

sources:
  blackbox:
    - name: bbe-ch-zh
      origin: zurich
      server: "blackbox-exporter:{{ bbe.port }}"
      auth:
    - name: bbe-fr-par
      origin: paris
      server: "bbe-paris.idev-fsd.ml:80"
      auth: '{{ auth.legacy }}'
  ressenti:
    - name: res-ch-zh
      module: firefox
      origin: zurich
      server: prob.86.119.40.68.nip.io
      auth: '{{ auth.legacy }}'
    - name: res-fr-par
      module: firefox
      origin: paris
      server: ressenti-paris.idev-fsd.ml
      auth: '{{ auth.legacy }}'
    - name: res-fr-par2
      module: firefox
      origin: paris2
      server: ressenti-paris2.idev-fsd.ml
      auth: '{{ auth.legacy }}'
