---
# tasks file for idevfsd-traefik
# ----------------------------------------------------------------- static files

- name: Copy traefik static files
  copy:
    src: "{{ role_path }}/files/"
    dest: "{{traefik.install_path}}/"
  tags:
    - traefik_copy
    - statics_files_copy
