debug = false

logLevel = "DEBUG"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.auth]
      [entryPoints.http.auth.basic]
      usersFile = "/htpasswd"


  [entryPoints.https]
  address = ":443"

  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "nip.io"
watch = true
exposedByDefault = false

[acme]
email = "giovanni.cangiani@epfl.ch"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"

