- name: Run alert telegram bot
  docker_container:
    name: alert-tg-bot
    image: epflsi/alert-tg-bot
    pull: "{{ 'no' if runenv == 'prod' else 'yes' }}"
    env:
      TELEGRAM_BOT_TOKEN: "{{ _noc_secrets.telegram.TOKEN }}"
      DEBUG: "{{ 'false' if runenv == 'prod' else 'true' }}"
    detach: yes
    restart_policy: unless-stopped
    network_mode: "{{ backend_network_name }}"
