version: '3'
services:
# https://github.com/prometheus/node_exporter#using-docker
  nodeexporter:
    image: quay.io/prometheus/node-exporter
    restart: always
    pid: "host"
#    network_mode: host
    networks:
      - {{ traefik.network }}
      - default
    command:
      - '--path.rootfs=/host'
    volumes:
      - /:/host:ro,rslave
    labels:
      - "traefik.port={{ nodeexporter.port }}"
      - "traefik.domain={{ frontend.domain }}"
      - "traefik.frontend.rule=Host:nodeexporter{{ dnspostfix }}.{{ frontend.domain }}"
      - "traefik.docker.network={{ traefik.network }}"
      - "traefik.enable=true"
{% if frontend.protocol == 'https' %}
      - "traefik.frontend.redirect.entryPoint={{ frontend.protocol }}"
{% endif %}


networks:
  {{ traefik.network }}:
    external: true
