{
 "title": "template-Ressenti",
 "tags": [ "ressenti" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "origin",
    "label": "Origin",
    "query": "label_values(probe_duration_seconds,origin)"
   },
   {
    "name": "slug",
    "label": "Site",
    "query": "label_values(probe_duration_seconds,slug)"
   }
  ]
 },
 "panels": [
  {
   "title": "Blackbox / http code",
   "type": "graph",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_http_status_code{probe=\"blackbox\", slug=~\"$slug\", origin=~\"$origin\"}",
     "legendFormat": "{{slug}} [{{origin}}]"
    }
   ]
  },
  {
   "title": "Ressenti (full page ready)",
   "type": "graph",
   "description": "Time to full page generation",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{probe=\"ressenti_firefox\", slug=~\"$slug\", origin=~\"$origin\"}",
     "legendFormat": " {{slug}} [{{origin}}]"
    }
   ]
  },
  {
   "title": "Blackbox / probe (sec)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{probe=\"blackbox\", slug=~\"$slug\", origin=~\"$origin\"}",
     "legendFormat": "{{slug}} [{{origin}}]: dns"
    },
    {
     "expr": "probe_duration_seconds{probe=\"blackbox\", slug=~\"$slug\", origin=~\"$origin\"}",
     "legendFormat": "{{slug}}: total  [{{origin}}]"
    },
    {
     "expr": "clamp_min(probe_http_duration_seconds{probe=\"blackbox\", slug=~\"$slug\", origin=~\"$origin\"}, 0)",
     "legendFormat": "{{slug}}: {{phase}} [{{origin}}]"
    }
   ]
  },
  {
   "title": "Blackbox / ssl cert expire",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "1000 * probe_ssl_earliest_cert_expiry{probe=\"blackbox\", slug=~\"$slug\", origin=~\"$origin\"}",
     "legendFormat": "{{slug}}"
    }
   ]
  }
 ]
}