version: '3'
services:
  blackbox-exporter:
    container_name: blackbox-exporter
    image: prom/blackbox-exporter:v0.14.0
    volumes:
      - ./config:/config
    command: --config.file=/config/blackbox.yml
    restart: always
    networks:
      - {{ backend_network_name }}
      - default
    labels:
      - "traefik.domain={{ frontend.domain }}"
      - "traefik.frontend.rule=Host:bbe{{ dnspostfix }}.{{ frontend.domain }}"
      - "traefik.docker.network={{ backend_network_name }}"
      - "traefik.enable=true"
      - "traefik.port={{ bbe.port }}"
      - "traefik.frontend.auth.basic={{ frontend.htpass }}"

networks:
  {{ backend_network_name }}:
    external: true
