---
# tasks file for idevfsd-noc using docker-compose

# ------------------------------------------------ Check that keybase is mounted
- name: Copy alertmanager static files
  copy:
    src: "{{ role_path }}/files/"
    dest: "{{ noc.install_path }}/alertmanager/"
  tags:
    - alertmanager_copy
    - statics_files_copy
    
