- name: Check if environment is set
  hosts: all
  tasks:
    -
      debug:
        msg: "Starting ansible with {{ runenv }} environment."

- name: Importing global secrets from keybase
  hosts: all
  tasks:
    - include_vars: "{{ playbook_dir }}/vars/main.yml"
      tags: always

- name: External NOC
  hosts: noc
  gather_facts: no   # Not yet
  # Variables common to all roles
  vars:
    - install_path: "{{ noc_install_path }}"
    - frontend:
        domain: idev-fsd.ml
        protocol: https
        htpass: '{{ _noc_secrets.frontend.htpasswd }}'
    # vars for nickjj.docker
    - docker__edition: "ce"
    - docker__channel: ["stable"]
    - docker__state: "present"
    - docker__users: ["{{ ansible_user }}"]
    - traefik:
        network: traefik
        install_path: '{{ noc_install_path }}/traefik'
  roles:
    - name: docker
      role: nickjj.docker
      become: yes
      become_user: root
      tags: docker

    - name: traefik
      role: ../roles/traefik
      tags: traefik

    - name: noc
      role: ../roles/noc
      tags: noc

    - name: alertmanager
      role: ../roles/alertmanager
      tags:
        - noc
        - alertmanager

    - name: blackbox_exporter
      role: ../roles/blackbox_exporter
      tags:
        - noc
        - bbe

    - name: grafana
      role: ../roles/grafana
      tags:
        - noc
        - grafana

    - name: node_exporter
      role: ../roles/node_exporter
      tags:
        - noc
        - nodeexporter

    - name: prometheus
      role: ../roles/prometheus
      tags:
        - noc
        - prometheus

    - name: pushgateway
      role: ../roles/pushgateway
      tags:
        - noc
        - pushgateway
