- name: Check if environment is set
  hosts: all
  tasks:
    -
      debug:
        msg: "Starting ansible with {{ runenv }} environment."

- name: External NOC
  hosts: noc
  gather_facts: no   # Not yet
  # Variables common to all roles
  vars:
    - install_path: "{{ noc_install_path }}"
    - frontend:
        domain: idev-fsd.ml
        protocol: https
        htpass: "{{ 'ENC[PKCS7,MIIBuQYJKoZIhvcNAQcDoIIBqjCCAaYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAJRyWwSK8uBp5AscvBZiMt34Xm0oSEbw2tT4OwjOY0o6xLJEnCwvkDpepbzYXgc67Xv+mznaaOY34TacW/nLOcC0xLnlamKj62J0vacqIZSCBhvgFT0kUOcovXSZyqmRt3iKPcfV+01BoXqUAKqUBBaMbEyyizAZP0xdU02ParPmetlgyWuZqesDfx1Owa8uSYD42DAWRvxK0Btql1BBXlc8mh9GGe3fB5EcsF7sp9nqTxZ9Fdv8kALxO/bUHaJlhu9jXno9gncO56SCLMSu24ETEOEWFpw/Kfbn0LH9kCqjZhkGdj7lQkxMKrj45RXaZW+53gCxsrAaIbTfhfkz6gjB8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBAzfXIu4CDeFs9Dd00vGANGgFDmZH4QY32Rn44N9EmMkf4UYiFSo2g91wg/F4Isvjckwxhf8YAdSgVz8tC5WU8ODpg10E052XyB1Rqul8t3vk2H0JhvGqc49uL+Bnw2OqWUxQ==]' | eyaml }}"
    # vars for nickjj.docker
    - docker__edition: "ce"
    - docker__channel: ["stable"]
    - docker__state: "present"
    - docker__users: ["{{ ansible_user }}"]
    - traefik:
        network: traefik
        install_path: '{{ noc_install_path }}/traefik'
  roles:
    - name: docker
      role: nickjj.docker
      become: yes
      become_user: root
      tags: docker

    - name: traefik
      role: ../roles/traefik
      tags: traefik

    - name: noc
      role: ../roles/noc
      tags: noc

    - name: alertmanager
      role: ../roles/alertmanager
      tags:
        - noc
        - alertmanager

    - name: blackbox_exporter
      role: ../roles/blackbox_exporter
      tags:
        - noc
        - bbe

    - name: grafana
      role: ../roles/grafana
      tags:
        - noc
        - grafana

    - name: node_exporter
      role: ../roles/node_exporter
      tags:
        - noc
        - nodeexporter

    - name: prometheus
      role: ../roles/prometheus
      tags:
        - noc
        - prometheus

    - name: pushgateway
      role: ../roles/pushgateway
      tags:
        - noc
        - pushgateway
