version: '3'
services:
  grafana:
    image: grafana/grafana
    restart: always
    environment:
      # when plugin list changes docker-compose up -d --build grafana is required
      GF_INSTALL_PLUGINS: "{{ grafana.plugins | join(',') }}"

      # GF_RENDERING_SERVER_URL: http://renderer:8081/render
      # GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      # GF_LOG_FILTERS: rendering:debug

    volumes:
      - "{{ noc.install_path }}/data/grafana/data:/var/lib/grafana"
      - "{{ noc.install_path }}/data/grafana/conf/grafana.ini:/etc/grafana/grafana.ini"
      - "{{ noc.install_path }}/data/grafana/provisioning:/etc/grafana/provisioning"
    networks:
      - {{ backend_network_name }}
      - default
    labels:
      - "traefik.port={{ grafana.port }}"
      - "traefik.domain={{ frontend.domain }}"
      - "traefik.frontend.rule=Host:grafana{{ dnspostfix }}.{{ frontend.domain }}"
      - "traefik.docker.network={{ backend_network_name }}"
      - "traefik.enable=true"
{% if frontend.protocol == 'https' %}
      - "traefik.frontend.redirect.entryPoint={{ frontend.protocol }}"
{% endif %}

  # renderer:
  #   image: grafana/grafana-image-renderer:latest
  #   ports:
  #     - 8081

networks:
  {{ backend_network_name }}:
    external: true
