---
# tasks file for idevfsd-noc using docker-compose

- name: Get URLs from wp-veritas API
  local_action:
    module: shell
    cmd: "{{ role_path }}/vars/sites_from_veritas"
  register: sites_from_veritas

- name: Log urls
  check_mode: no
  debug:
    msg: "{{urls}}"

# ------------------------------------------------------------------ Directories

- name: Create writable directories to be used as mount points
  file:
    path: "{{ noc.install_path }}/{{ item }}"
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"
  with_items:
    - data/prometheus

# ----------------------------------------------------------------- static files

- name: Copy prometheus static files
  copy:
    src: "{{ role_path }}/files/"
    dest: "{{ noc.install_path }}/prometheus/"
  tags:
    - prometheus_copy
    - statics_files_copy

# -------------------------------------------------------------------- Templates

- name: Copy prometheus template configs
  template:
    src: "prometheus/{{ item }}"
    dest: "{{ noc.install_path }}/prometheus/{{ item }}"
  with_items:
    - prometheus.yml
    - rules/c2c_federate.yml
  register: prometheus_config_files
  tags:
    - prometheus_copy
    - statics_files_copy
