---
# tasks file for idevfsd-noc using docker-compose

# - name: Random debug
#   debug:
#     msg: "htpass: {{ frontend.htpass | htpasswd }}"

# ------------------------------------------------ Check that keybase is mounted


- name: Copy alertmanager static files
  copy:
    src: "alertmanager/"
    dest: "{{ noc.install_path }}/alertmanager/"

# -------------------------------------------------------------------- Templates

# - name: Copy docker-compose file
#   template:
#     # src: "docker-compose.yml"
#     src: "docker-compose.yml"
#     dest: "{{ noc.install_path }}/docker-compose.yml"
#   register: compose_file

- name: Copy Makefile
  template:
    src: "Makefile"
    dest: "{{ noc.install_path }}/Makefile"
  register: compose_file
