---
# tasks file for idevfsd-noc using docker-compose

# - name: Random debug
#   debug:
#     msg: "htpass: {{ frontend.htpass | htpasswd }}"

# ------------------------------------------------ Check that keybase is mounted


- name: Copy alertmanager static files
  copy:
    src: "alertmanager/"
    dest: "{{ noc.install_path }}/alertmanager/"
