- name: External Noc
  hosts: noc
  gather_facts: no   # Not yet
  # Variables common to all roles
  vars:
    - container_prefix: "idevfsd2-"
    - install_path: /root/anoc3
    -
      frontend:
        domain: idev-fsd.ml
        protocol: https
        htpass: "{{ 'ENC[PKCS7,MIIBqQYJKoZIhvcNAQcDoIIBmjCCAZYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAQiRgtfEm9tVbN4M32YYGbdR235NKi8fh0H1o689QjW25YbdjVaGRRuJjwpl2FHq+TPNcu6+MEAFJXo25Q+wiFPRt2md1X2z+eiILCWcvEljeN2NoppSYHfRrE7OYQwA81bn4HJQKO6KUoJj/3CNGMY9MAtsdm5xnXh0dtz8nX2Ti/zZLSs9OOJGhaBhNN3C28FJJG7TYR09pNF1t6i+jyuH2EKDWJaPSupTzsnPwdhEt4UJSZEyN6fDqfGKHV4/C+qo4JZe7/QuTI7fEAlbl7d33s3BcgY4/eAozBCLB6M2Vltq00Ol2toImBkzmUYoiimjG3fFba+V/N/LguelKHTBsBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBDO9iweYhLHIpkqW9b6udBcgEDxRsmfqdXrqvo2wMVHhfEXKbl1guuxAwc3i/QiMGCSUOUkzkpXmoM6le5UVH0vbtiaGsvl6UiacmdsEI1ZK+Au]' | eyaml }}"

  roles:
    - idevfsd-traefik
    - idevfsd-bbe
    - idevfsd-noc

# - name: External bbox
#   hosts: bbox
#   gather_facts: no   # Not yet
#   # Variables common to all roles
#   vars:
#     - install_path: /ubuntu/anoc2
#     - container_prefix: "idevfsd2-"
#     -
#       frontend:
#         domain: idev-fsd.ml
#         protocol: https
#         htpass: "{{ 'ENC[PKCS7,MIIBqQYJKoZIhvcNAQcDoIIBmjCCAZYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAQiRgtfEm9tVbN4M32YYGbdR235NKi8fh0H1o689QjW25YbdjVaGRRuJjwpl2FHq+TPNcu6+MEAFJXo25Q+wiFPRt2md1X2z+eiILCWcvEljeN2NoppSYHfRrE7OYQwA81bn4HJQKO6KUoJj/3CNGMY9MAtsdm5xnXh0dtz8nX2Ti/zZLSs9OOJGhaBhNN3C28FJJG7TYR09pNF1t6i+jyuH2EKDWJaPSupTzsnPwdhEt4UJSZEyN6fDqfGKHV4/C+qo4JZe7/QuTI7fEAlbl7d33s3BcgY4/eAozBCLB6M2Vltq00Ol2toImBkzmUYoiimjG3fFba+V/N/LguelKHTBsBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBDO9iweYhLHIpkqW9b6udBcgEDxRsmfqdXrqvo2wMVHhfEXKbl1guuxAwc3i/QiMGCSUOUkzkpXmoM6le5UVH0vbtiaGsvl6UiacmdsEI1ZK+Au]' | eyaml }}"

#   roles:
#     - idevfsd-traefik
#     - idevfsd-bbe
