- name: Check if environment is set
  hosts: all
  tasks:
    -
      debug:
        msg: "Starting ansible with {{ runenv }} environment."


- name: External NOC
  hosts: noc

  gather_facts: no   # Not yet
  # Variables common to all roles
  vars:
    - install_path: "{{ noc_install_path }}"
    - frontend:
        domain: idev-fsd.ml
        protocol: https
        htpass: "{{ 'ENC[PKCS7,MIIBqQYJKoZIhvcNAQcDoIIBmjCCAZYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAQiRgtfEm9tVbN4M32YYGbdR235NKi8fh0H1o689QjW25YbdjVaGRRuJjwpl2FHq+TPNcu6+MEAFJXo25Q+wiFPRt2md1X2z+eiILCWcvEljeN2NoppSYHfRrE7OYQwA81bn4HJQKO6KUoJj/3CNGMY9MAtsdm5xnXh0dtz8nX2Ti/zZLSs9OOJGhaBhNN3C28FJJG7TYR09pNF1t6i+jyuH2EKDWJaPSupTzsnPwdhEt4UJSZEyN6fDqfGKHV4/C+qo4JZe7/QuTI7fEAlbl7d33s3BcgY4/eAozBCLB6M2Vltq00Ol2toImBkzmUYoiimjG3fFba+V/N/LguelKHTBsBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBDO9iweYhLHIpkqW9b6udBcgEDxRsmfqdXrqvo2wMVHhfEXKbl1guuxAwc3i/QiMGCSUOUkzkpXmoM6le5UVH0vbtiaGsvl6UiacmdsEI1ZK+Au]' | eyaml }}"
    - traefik:
        network: traefik
        install_path: '{{ noc_install_path }}/traefik'
    - image_version:
        alertmanager: "v0.19.0"
        bbe: "v0.16.0"
        grafana: "6.4.4"
        nodeexporter: "v0.18.1"
        prometheus: "v2.14.0"
        pushgateway: "v1.0.0"
        traefik: "1.7"

  roles:
    - name: traefik
      tags: traefik

    - name: noc
      tags: noc

    - name: alertmanager
      tags:
        - noc
        - alertmanager

    - name: blackbox_exporter
      tags:
        - noc
        - bbe

    - name: grafana
      tags:
        - noc
        - grafana

    - name: node_exporter
      tags:
        - noc
        - nodeexporter

    - name: prometheus
      tags:
        - noc
        - prometheus

    - name: pushgateway
      tags:
        - noc
        - pushgateway

  tasks:
    - name: "Start services in docker-compose"
      # vars:
      #   ansible_python_interpreter: /usr/bin/python3
      docker_compose:
        project_src: "{{ noc_install_path }}"
        state: present
        services: "{{ active_services }}"
        restarted: yes
        # pull: yes
        # build: yes

# - name: External blackbox exporter
#   hosts: bbox
#   gather_facts: no   # Not yet
#   # Variables common to all roles
#   vars:
#     - install_path: /ubuntu/anoc2
#     -
#       frontend:
#         domain: idev-fsd.ml
#         protocol: https
#         htpass: "{{ 'ENC[PKCS7,MIIBqQYJKoZIhvcNAQcDoIIBmjCCAZYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAQiRgtfEm9tVbN4M32YYGbdR235NKi8fh0H1o689QjW25YbdjVaGRRuJjwpl2FHq+TPNcu6+MEAFJXo25Q+wiFPRt2md1X2z+eiILCWcvEljeN2NoppSYHfRrE7OYQwA81bn4HJQKO6KUoJj/3CNGMY9MAtsdm5xnXh0dtz8nX2Ti/zZLSs9OOJGhaBhNN3C28FJJG7TYR09pNF1t6i+jyuH2EKDWJaPSupTzsnPwdhEt4UJSZEyN6fDqfGKHV4/C+qo4JZe7/QuTI7fEAlbl7d33s3BcgY4/eAozBCLB6M2Vltq00Ol2toImBkzmUYoiimjG3fFba+V/N/LguelKHTBsBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBDO9iweYhLHIpkqW9b6udBcgEDxRsmfqdXrqvo2wMVHhfEXKbl1guuxAwc3i/QiMGCSUOUkzkpXmoM6le5UVH0vbtiaGsvl6UiacmdsEI1ZK+Au]' | eyaml }}"

#   roles:
#     - idevfsd-traefik
#     - idevfsd-bbe
