- name: Check if environment is set
  hosts: all
  tasks:
    - 
      debug:
        msg: "Starting ansible with {{ runenv }} environment."

- name: External Noc
  hosts: noc
  gather_facts: no   # Not yet
  # Variables common to all roles
  vars:
    - container_prefix: "idevfsd2-"
    - install_path: "{{ noc_install_path }}"
    - frontend:
        domain: idev-fsd.ml
        protocol: https
        htpass: "{{ 'ENC[PKCS7,MIIBqQYJKoZIhvcNAQcDoIIBmjCCAZYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAQiRgtfEm9tVbN4M32YYGbdR235NKi8fh0H1o689QjW25YbdjVaGRRuJjwpl2FHq+TPNcu6+MEAFJXo25Q+wiFPRt2md1X2z+eiILCWcvEljeN2NoppSYHfRrE7OYQwA81bn4HJQKO6KUoJj/3CNGMY9MAtsdm5xnXh0dtz8nX2Ti/zZLSs9OOJGhaBhNN3C28FJJG7TYR09pNF1t6i+jyuH2EKDWJaPSupTzsnPwdhEt4UJSZEyN6fDqfGKHV4/C+qo4JZe7/QuTI7fEAlbl7d33s3BcgY4/eAozBCLB6M2Vltq00Ol2toImBkzmUYoiimjG3fFba+V/N/LguelKHTBsBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBDO9iweYhLHIpkqW9b6udBcgEDxRsmfqdXrqvo2wMVHhfEXKbl1guuxAwc3i/QiMGCSUOUkzkpXmoM6le5UVH0vbtiaGsvl6UiacmdsEI1ZK+Au]' | eyaml }}"
    # vars for nickjj.docker
    - docker__edition: "ce"
    - docker__channel: ["stable"]
    - docker__state: "present"
    - docker__users: ["{{ ansible_user }}"]
    - traefik:
        network: traefik
        install_path: '{{ noc_install_path }}/traefik'
  roles:
    - role: nickjj.docker
      become: yes
      become_user: root
      tags: docker
    - idevfsd-traefik
    - idevfsd-bbe
      tags: bbe
    - idevfsd-noc
      tags: noc

# - name: External bbox
#   hosts: bbox
#   gather_facts: no   # Not yet
#   # Variables common to all roles
#   vars:
#     - install_path: /ubuntu/anoc2
#     - container_prefix: "idevfsd2-"
#     -
#       frontend:
#         domain: idev-fsd.ml
#         protocol: https
#         htpass: "{{ 'ENC[PKCS7,MIIBqQYJKoZIhvcNAQcDoIIBmjCCAZYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAQiRgtfEm9tVbN4M32YYGbdR235NKi8fh0H1o689QjW25YbdjVaGRRuJjwpl2FHq+TPNcu6+MEAFJXo25Q+wiFPRt2md1X2z+eiILCWcvEljeN2NoppSYHfRrE7OYQwA81bn4HJQKO6KUoJj/3CNGMY9MAtsdm5xnXh0dtz8nX2Ti/zZLSs9OOJGhaBhNN3C28FJJG7TYR09pNF1t6i+jyuH2EKDWJaPSupTzsnPwdhEt4UJSZEyN6fDqfGKHV4/C+qo4JZe7/QuTI7fEAlbl7d33s3BcgY4/eAozBCLB6M2Vltq00Ol2toImBkzmUYoiimjG3fFba+V/N/LguelKHTBsBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBDO9iweYhLHIpkqW9b6udBcgEDxRsmfqdXrqvo2wMVHhfEXKbl1guuxAwc3i/QiMGCSUOUkzkpXmoM6le5UVH0vbtiaGsvl6UiacmdsEI1ZK+Au]' | eyaml }}"

#   roles:
#     - idevfsd-traefik
#     - idevfsd-bbe
