- name: Install yum utils
  package:
    name: yum-utils
    state: present

- name: Install device-mapper-persistent-data
  package:
    name: device-mapper-persistent-data
    state: present

- name: Install lvm2
  package:
    name: lvm2
    state: present

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  become: yes

# - name: Enable Docker Edge repo
#   ini_file:
#     dest: /etc/yum.repos.d/docker-ce.repo
#     section: 'docker-ce-edge'
#     option: enabled
#     value: 0
#   become: yes

# - name: Enable Docker Test repo
#   ini_file:
#     dest: /etc/yum.repos.d/docker-ce.repo
#     section: 'docker-ce-test'
#     option: enabled
#     value: 0
#   become: yes

- name: Enable RHEL extra repo
  ini_file:
    dest: /etc/yum.repos.d/redhat.repo 
    section: 'rhel-7-server-extras-rpms'
    option: enabled
    value: 1
  become: yes

- name: Install Docker
  package:
    name: docker-ce
    state: latest
  become: yes

- name: Install docker-compose
  package:
    name: docker-compose
    state: latest
  become: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

# - name: Add user vagrant to docker group
#   user:
#     name: vagrant
#     groups: docker
#     append: yes
#   become: yes
