---
# tasks file for idevfsd-noc using docker-compose

# -------------------------------------------------------------------- Templates

- name: Copy pushgateway static files
  copy:
    src: "{{ role_path }}/files/"
    dest: "{{ noc.install_path }}/pushgateway/"
  tags:
    - pushgateway_copy
